//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhMedium.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorPublication
    {
        public string Id { get; set; }
        public string AuthorId { get; set; }
        public string PublicationId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
