//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhMedium.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public string Id { get; set; }
        public string Path { get; set; }
        public string PublicationId { get; set; }
        public string UserId { get; set; }
        public string ArticleId { get; set; }
        public string TopicId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
